version: "3.4"

services:
  fdx-pgsql:
    platform: linux/amd64
    container_name: fdx-pgsql
    image: postgres:latest
    ports:
      - "5435:5432"
    volumes:
      - fdx-pgsql-db:/usr/local/postgres
    environment:
      - POSTGRES_DB=fuel-indexer
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  fdx-pgsql-db:
