[package]
name = "fdx_sync"
edition.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fdx_core = { path = "../core" }
tokio = { workspace = true }
